# Generated by Django 5.1.6 on 2025-12-19 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('plus_two_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='+2 Percentage')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Collection Form Entry',
                'verbose_name_plural': 'Collection Form Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='formapp_col_email_94012e_idx'), models.Index(fields=['phone_number'], name='formapp_col_phone_n_10a860_idx')],
            },
        ),
    ]
