# Generated by Django 6.0 on 2025-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='colleges_selected',
            field=models.TextField(blank=True, null=True, verbose_name='Colleges Selected'),
        ),
    ]
