# Generated by Django 6.0 on 2025-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_collectionform_colleges_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='course_selected',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Selected'),
        ),
    ]
