# Generated by Django 6.0 on 2025-12-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_collectionform_course_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='aggregate_percentage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Aggregate Percentage%/CGPA'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('10th Standard', '10th Standard'), ('12th Standard', '12th Standard'), ('Diploma', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree")], max_length=50, null=True, verbose_name='Highest Qualification'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Passing'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='plus_two_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='+2 Percentage'),
        ),
    ]
