# Generated by Django 6.0 on 2025-12-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_collectionform_aggregate_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionform',
            name='current_location',
        ),
    ]
