# Generated by Django 6.0 on 2025-12-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_remove_collectionform_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra Data'),
        ),
    ]
