# Generated by Django 6.0 on 2025-12-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('login_id', models.CharField(max_length=50, unique=True, verbose_name='Login ID')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('active_status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='collectionform',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='formapp.staff', verbose_name='Assigned Staff'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='formapp.staff', verbose_name='Assigned Staff'),
        ),
    ]
