# Generated by Django 6.0 on 2026-01-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_staff_collectionform_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='document_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Document Links'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
