# Generated by Django 6.0 on 2026-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_staff_address_staff_date_of_joining_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
