# Generated by Django 6.0 on 2026-01-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_collectionform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
    ]
