# Generated by Django 6.0 on 2026-01-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_collectionform_is_read_enquiry_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionform',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_read',
        ),
    ]
