# Generated by Django 6.0 on 2026-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_remove_collectionform_is_read_remove_enquiry_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
