# Generated by Django 6.0 on 2026-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_collectionform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionform',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='document_links',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Connected', 'Connected')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
