# Generated by Django 6.0 on 2026-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_remove_collectionform_status_remove_staff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionform',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
