# Generated by Django 5.1.6 on 2026-01-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_alter_collectionform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
