# Generated by Django 6.0 on 2026-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_collectionform_is_read_alter_collectionform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Connected', 'Connected'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
