# Generated by Django 6.0 on 2026-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Connected', 'Connected')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
