# Generated by Django 5.1.6 on 2026-01-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_enquiry_is_read_alter_enquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='is_read',
        ),
    ]
