# Generated by Django 6.0 on 2026-01-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0020_remove_enquiry_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionform',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='collectionform',
            name='status',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
    ]
