# Generated by Django 6.0 on 2026-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0021_remove_collectionform_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='collectionform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
