# Generated by Django 6.0 on 2026-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0026_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='staff', max_length=10, verbose_name='Role'),
        ),
    ]
