# Generated by Django 6.0 on 2026-01-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0028_staff_address_staff_date_of_joining_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='official_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Official Staff Photo (Base64)'),
        ),
    ]
