# Generated by Django 5.1.6 on 2026-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0029_staff_official_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
