# Generated by Django 5.1.6 on 2026-01-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0030_collectionform_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Connected', 'Connected'), ('Follow Up', 'Follow Up')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
