# Generated by Django 5.1.6 on 2026-01-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0031_enquiry_follow_up_date_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='collectionform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Follow Up', 'Follow Up')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
