# Generated by Django 5.1.6 on 2026-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0033_staffnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.DeleteModel(
            name='StaffNote',
        ),
    ]
