# Generated by Django 6.0 on 2026-01-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0034_alter_collectionform_email_delete_staffnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionform',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Viewed At'),
        ),
    ]
