# Generated by Django 6.0 on 2026-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0035_collectionform_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Viewed At'),
        ),
    ]
