# Generated by Django 5.1.6 on 2026-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0036_enquiry_viewed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['assigned_staff'], name='formapp_col_assigne_96d991_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['created_at'], name='formapp_col_created_92ea3e_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionform',
            index=models.Index(fields=['is_read', 'status'], name='formapp_col_is_read_252f33_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['phone'], name='formapp_enq_phone_f7afee_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['assigned_staff'], name='formapp_enq_assigne_97f90e_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='formapp_enq_created_bfae29_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['is_read', 'status'], name='formapp_enq_is_read_ddc62b_idx'),
        ),
    ]
