# Generated by Django 6.0 on 2026-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0037_collectionform_formapp_col_assigne_96d991_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
