# Generated by Django 6.0 on 2026-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0038_alter_collectionform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='collectionform',
            name='last_name',
        ),
        migrations.AddField(
            model_name='collectionform',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
