# Generated by Django 6.0 on 2026-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0039_remove_collectionform_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('login_id', models.CharField(max_length=50, unique=True, verbose_name='Login ID')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('active_status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
