# Generated by Django 6.0 on 2026-01-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
