# Generated by Django 6.0 on 2026-02-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_revoked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
